const FILE_UPLOADS_URL = process.env.FILE_UPLOADS_URL!; // http://localhost:4000/uploads/
const PAGINATION_SET_SIZE = 7;
const COMMENT_PAGINATION_SET_SIZE = 8;
const REPUTATION_FOR_LIKE = 10;
const REPUTATION_FOR_DISLIKE = -5;
const DECISION_WON_REPUTATION = 1000;
const DECISION_LOST_REPUTATION = 200;
const SITEMAP_PAGINATION_LIMIT = 7000;
const ADMIN_MAIL_ID = process.env.ADMIN_MAIL_ID || "";

export {
  FILE_UPLOADS_URL,
  PAGINATION_SET_SIZE,
  COMMENT_PAGINATION_SET_SIZE,
  REPUTATION_FOR_DISLIKE,
  REPUTATION_FOR_LIKE,
  DECISION_LOST_REPUTATION,
  DECISION_WON_REPUTATION,
  SITEMAP_PAGINATION_LIMIT,
  ADMIN_MAIL_ID,
};
