const CONTENT_CASES = {
  SHOW_POST_CONTENT: "content/SHOW_POST_CONTENT",
  HIDE_POST_CONTENT: "content/HIDE_POST_CONTENT",

  SHOW_POST_ORSIC: "content/SHOW_POST_ORSIC",
  HIDE_POST_ORSIC: "content/HIDE_POST_ORSIC",

  SHOW_POST_IMAGE: "content/SHOW_POST_IMAGE",
  HIDE_POST_IMAGE: "content/HIDE_POST_IMAGE",

  SHOW_EDIT_PROFILE: "content/SHOW_EDIT_PROFILE",
  HIDE_EDIT_PROFILE: "content/HIDE_EDIT_PROFILE",

  SHOW_LOGIN_DIALOG: "content/SHOW_LOGIN_DIALOG",
  HIDE_LOGIN_DIALOG: "content/HIDE_LOGIN_DIALOG",
};

export default CONTENT_CASES;
