'use client';

import List from '@mui/material/List';
import ListItemButton from '@mui/material/ListItemButton';
import ListItemAvatar from '@mui/material/ListItemAvatar';
import ListItemText from '@mui/material/ListItemText';
import Avatar from '@mui/material/Avatar';
import Drawer from '@mui/material/Drawer';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import colors from '@/logic/colors';

const channelsDrawerWidth = '25%';

export default function Channels() {
    return (
        <Drawer
            variant="permanent"
            anchor="left"
            sx={{
                width: channelsDrawerWidth,
                flexShrink: 0,
                '& .MuiDrawer-root': {
                    position: 'absolute',
                },
                [`& .MuiDrawer-paper`]: {
                    width: channelsDrawerWidth,
                    boxSizing: 'border-box',
                    position: 'absolute',
                    backgroundColor: colors.slate[800],
                },
                display: {
                    xs: 'none',
                    lg: 'block',
                },
            }}
            PaperProps={{
                sx: {
                    border: 0,
                },
            }}
        >
            <Toolbar />
            <Box sx={{ overflow: 'auto' }}>
                <List
                    sx={{
                        flex: 1 / 4,
                        height: '100%',
                        overflowY: 'scroll',
                        position: 'sticky',
                    }}
                >
                    {channels.map(({ primary, secondary, person }, index) => (
                        <ListItemButton key={index + person}>
                            <ListItemAvatar>
                                <Avatar alt="Profile Picture" src={person} />
                            </ListItemAvatar>
                            <ListItemText
                                primary={primary}
                                secondary={secondary}
                            />
                        </ListItemButton>
                    ))}
                </List>
            </Box>
        </Drawer>
    );
}

const channels = [
    {
        primary: 'Brunch this week?',
        secondary:
            "I'll be in the neighbourhood this week. Let's grab a bite to eat",
        person: 'mui.com/static/images/avatar/5.jpg',
    },
    {
        primary: 'Birthday Gift',
        secondary: `Do you have a suggestion for a good present for John on his work
        anniversary. I am really confused & would love your thoughts on it.`,
        person: '/static/images/avatar/1.jpg',
    },
    {
        primary: 'Recipe to try',
        secondary:
            'I am try out this new BBQ recipe, I think this might be amazing',
        person: '/static/images/avatar/2.jpg',
    },
    {
        primary: 'Yes!',
        secondary: 'I have the tickets to the ReactConf for this year.',
        person: '/static/images/avatar/3.jpg',
    },
    {
        primary: "Doctor's Appointment",
        secondary:
            'My appointment for the doctor was rescheduled for next Saturday.',
        person: '/static/images/avatar/4.jpg',
    },
    {
        primary: 'Discussion',
        secondary: `Menus that are generated by the bottom app bar (such as a bottom
        navigation drawer or overflow menu) open as bottom sheets at a higher elevation
        than the bar.`,
        person: '/static/images/avatar/5.jpg',
    },
    {
        primary: 'Summer BBQ',
        secondary: `Who wants to have a cookout this weekend? I just got some furniture
        for my backyard and would love to fire up the grill.`,
        person: '/static/images/avatar/1.jpg',
    },
];
