const USER_CASES = {
  LOGIN: "user/LOGIN",
  LOGOUT: "user/LOGOUT",
  SET_NOTIFICATIONS: "user/SET_NOTIFICATIONS",
  NOTIFICATIONS_READ: "user/NOTIFICATIONS_READ",
  SETUP_COMPLETE: "user/SETUP_COMPLETE",
};

export default USER_CASES;
