const APP_CASES = {
  SHOW_BARS: "app/SHOW_BARS",
  HIDE_BARS: "app/HIDE_BARS",
  SHOW_REPLY: "app/SHOW_REPLY",
  HIDE_REPLY: "app/HIDE_REPLY",
  SET_BIONIC_MODE: "app/SET_BIONIC_MODE",
  TOGGLE_BIONIC_MODE: "app/TOGGLE_BIONIC_MODE",
};

export default APP_CASES;
