name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy API
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}

          script: |
            cd orsive
            git pull origin main
            npm install
            cd apps/api
            npm run generate
            npm run migrate
            cd ..
            cd ..
            pm2 reload orsive-api
            echo 'Deployment successful to DigitalOcean'
